### ISSUE TITLE
The View

### ISSUE THREAD

**Issue by Co0sh** [Co0sh/BetonQuest-Editor#1]
The View needs to be done first in order to display the data on screen. Currently there are these parts planned:

* [x] **Main** - the main tab with NPC bindings, global locations, static events and variables, quest cancelers
* [x] **Conversations** - here the conversation will be edited
* [x] **Events**
* [x] **Conditions**
* [x] **Objectives**
* [x] **Items**
* [x] **Journal**

**Comment by Co0sh** [comment]
I'm rewriting the View classes into FXML, these will be more comfortable to use in a long run.

**Comment by Drehverschluss** [comment]
I dont know if thats the right place but u just want to ask if your Editor is allready useable?

Also do you still work on it? Just curious.

MFG

**Comment by Co0sh** [comment]
It's not usable yet, but it's not abandoned either. I'm too busy right now with my finals to code, and there's The Witcher too...

**Comment by Drehverschluss** [comment]
hehe well i understand :)
