### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Co0sh** [Co0sh/BetonQuest-Editor#14]
Please post all info about discovered bugs here :bug:

**Comment by Co0sh** [comment]
- [ ] Saving to directories is buggy. There's an error if subdirectories exist and it doesn't handle the case when selected directory is a root of package.
- [ ] Global variables are incorrectly loaded (no values)

**Comment by Co0sh** [comment]
- [ ] Bugged conversation tab when creating new set.

**Comment by HollishKid** [comment]
When trying to load my default package into the editor, I get the following error.
(you know my vast knowledge of error reading, so I have no idea whether this is relevant for you)

- [ ] http://pastebin.com/FFZqLiYK

**Comment by Co0sh** [comment]
You probably have an error in one of the conditions, in one of the player options in one of the conversations. The condition is prefixed with the name of a package which does not exist or at least is not loaded to the editor. Try to load all packages or fix that condition, it won't work anyway if there is such no package.

I think I need to add a nice error handling to package loading.

**Comment by Co0sh** [comment]
Hey @HollishKid, could you pull the latest changes and load those packages again? It should handle these errors.

**Comment by Co0sh** [comment]
Things I found:

- [ ] Recalculate tags and points on each request
- [ ] Add new pointer options to the end of the list, not the beginning. (index stuff)
- [ ] Select newly created option, focus option list
- [ ] Don't display name editing window when "creating" new tags from TextField

**Comment by rosedragon** [comment]
Found a massive bug that while importing my folder works great, when I compile it on the editor it take out all the player responses. Here are sample of 'before' and 'after'. If you need to get the whole folder, poke me on spigot forum. 
Before (notepad++)
http://pastebin.com/KyVpCDSt

After (editor)
http://pastebin.com/iyJtG39Q

regards,
rosedragon

**Comment by Co0sh** [comment]
Alright, I see the bug. Thanks ^^

No, it's not necessary, it's just how the YAML library saves its output. There is probably a way of changing that, but not now.
