### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Namnodorel** [Co0sh/BetonQuest-Editor#23]
I just compiled the editor, and even though it automatically switches to the correct language (German), the editor has problems with the special characters (ö, ä, ü, ß). Also the translation is not "smooth". I don't think it'd take too long for me to translate the strings to German, if you want to fix it ;)

**Comment by Co0sh** [comment]
Alright, I'll switch to German and see if I can fix these special characters. It should be fixable. Maybe the language file has the wrong encoding.

The current German translation is not complete, it was contributed by @IrusVirus a few days ago. You can add missing texts if you want :smile: I think I finished adding new texts, so it would be a good time to do that now. I'll be updating Polish translation myself tomorrow as well.

**Comment by Co0sh** [comment]
Yep, like I said, it's the wrong encoding. @IrusVirus has set _lang_de.properties_ to UTF-8 while the rest is ANSI. The encoding and line endings are apparently not the same across the whole code - I need to fix this. There should be UTF-8 and UNIX line endings everywhere. I'll do it when I have access to my own PC, on Saturday or Monday.

**Comment by IrusVirus** [comment]
German include special charakters like Ä Ö Ü... this works with "UTF-8 without BOM".

**Comment by Co0sh** [comment]
I know, but Java's `ResourceBundle` can't load UTF-8 by default. I would have to write my own `Control` class which would read UTF-8 encoded files. I could do that in the future, but for now let's just stick to ANSI and Unicode.

**Comment by Co0sh** [comment]
I've added a few texts, they are on the bottom of _lang.properties_ :smiley:

**Comment by Co0sh** [comment]
@Namnodorel, @IrusVirus I need one last text to translate before the release:
`Cannot add cross-conversation option here!`
Don't create PR, just tell me here :3
Thanks ^^

**Comment by Namnodorel** [comment]
I think that would be "Hier kann keine Gesprächsübergreifende Option hinzugefügt werden!". What I'm not sure about is if "option" should just be translated as "Option", because it can have a small meaning difference. But I guess you can just use it like that, when I'll have time to actually use the editor, I'll create a PR if it doesn't fit (or just write ir here).

**Comment by Co0sh** [comment]
Alright, great. Thanks :3
