### ISSUE TITLE
Small issue with red background

### ISSUE THREAD

**Issue by Namnodorel** [Co0sh/BetonQuest-Editor#34]
On the `conversations`-tab, if I create a new option, it is highlighted red because it has no content yet. But I think the red background should be removed, as soon as any content is filled in the text field. As it is now, the background stays until I click on the option.

**Comment by Co0sh** [comment]
I can't figure out any efficient way of doing it right now. I could remove and re-add all items in the list every time the user types a letter, but that doesn't seem to be a nice solution.

**Comment by Namnodorel** [comment]
I don't know JavaFX, but in Swing and the Android UI Framework the solution would be to override something like an onEdit-Event which gets fired every time the user types into the text field. Then it gets checked if the text field is empty or not, and the background is set to an appropiate color.
