### ISSUE TITLE
Can't create sub-packages

### ISSUE THREAD

**Issue by Namnodorel** [Co0sh/BetonQuest-Editor#36]
If I mark a package and the select New>Package, the package gets created next to the other packages instead of inside the one I want it to be in.

**Comment by Co0sh** [comment]
If you want structure like `set/sub1/sub2/pack` then you need to create package called `sub1-sub2-pack` in the `set`. It works exactly like adding packages to _config.yml_ in BetonQuest.

**Comment by Namnodorel** [comment]
Oh, ok ^^ Thanks
