### ISSUE TITLE
Still issues with special characters

### ISSUE THREAD

**Issue by Namnodorel** [Co0sh/BetonQuest-Editor#37]
I created some conversations with the editor, saved it, loaded it again and then this happened:
http://puu.sh/rfgV9/bfba6a5df0.png

**Comment by Co0sh** [comment]
I hate encoding bugs... Alright, thanks, I'll see how to fix it.

**Comment by Namnodorel** [comment]
Works now, thanks ^^

**Comment by Co0sh** [comment]
No problem. If you ever have problems with this again, check if the package you're trying to load is encoded in UTF-8. Spigot seems to use it now by default, so it shouldn't happen anyway.
