### ISSUE TITLE
Quest cancelers - Conditions

### ISSUE THREAD

**Issue by Tigerolves** [Co0sh/BetonQuest-Editor#45]
Hi there,

I just found out that when I set up the condition for the quest which I cancel, there is a bug that when you tick the prefix of ! then close and press OK, you edit it to open again and you will find out that the prefix of ! will be disabled by itself. It doesn't save the change for that.

**Comment by Co0sh** [comment]
@Tigerolves you can compile the editor immediately to get the fix or wait until I finish #41 and #42 and release an update via Sellfy email (in case you bought the editor). Sorry for the wait.

**Comment by Namnodorel** [comment]
Just an idea: How about you don't sell the editor itself but a tool which fetches and builds the editor automatically? That way the users which have bought it don't need to wait

**Comment by Co0sh** [comment]
@Namnodorel it's a nice idea (Spigot distributes releases this way), but I'd rather stick to standard release channel.

**Comment by Tigerolves** [comment]
When can I receive the Sellfy email? I'd bought the editor.

**Comment by Co0sh** [comment]
@Tigerolves I sent the emails two days ago and all arrived. Check your spam, maybe it's there?

**Comment by Tigerolves** [comment]
@Co0sh I got it. Yea it is in spam.

**Comment by Co0sh** [comment]
I'll have to add an information about this issue to the editor page.
