### ISSUE TITLE
Saving the package to a .zip file

### ISSUE THREAD

**Issue by Co0sh** [Co0sh/BetonQuest-Editor#5]
After #4 is achieved, this will be the next step - save the edited package to a file.

**Comment by Jack-McKalling** [comment]
So you're making it a standalone app I see.
May I ask why you're going for a zip file format though? Would it not be possible/easier to allow to select a directory on load and save to it directly (maybe as equal alternative to zip).

When it's a standalone app, it will reduce difficulties in developing quests, but it'd still be a lot of steps between editing and testing. Saving directly to directory might speed that up.

**Comment by Co0sh** [comment]
I'm planning on making three ways of loading the package:

* Open (a directory)
* Load (a .zip file)
* Import (via FTP/SFTP from the server)

The reason .zip and directory are separated is because JavaFX does not allow for choosing file _or_ directory, you have to be specific which type you want when creating the pop-up window.

I chose .zip to be the first option just because it's easier for me to just use one file instead of the whole directory.

**Comment by Jack-McKalling** [comment]
Fair enough. Cool ;)

**Comment by Co0sh** [comment]
The output is a little bit ugly (for example nested global variables don't get nested) but it's readable by BetonQuest. I need to test it a little bit to see if there are any differences _after parsing_ between original and saved package.

**Comment by MWFIAE** [comment]
From what I saw not everything loaded gets saved. 

Example: 

main.yml
cancel: {} (ok, fair enough I don't have any, maybe it doesn't include it because of this, but I'm wondering if the plugin is ok with it missing) 


journal_main_page:
  greeting:
    priority: 1
    text:
      de: 'Du hast eine Quest fuer den Gastwirt beendet!'
    conditions: 'sheep_kill_paid'
(not so ok, because it was just deleted... :/ )

**Comment by Co0sh** [comment]
I completely forgot about main page...

**Comment by Co0sh** [comment]
As with empty `cancel` section - BetonQuest doesn't mind this, but it shouldn't happen. Quite strange, I remember adding `isEmpty` check :confused:
